### ISSUE TITLE
Build runner error when attempting to generate simple one-to-many relationship

### ISSUE THREAD

**Issue by kylehayes** [schultek/stormberry#30]
A simple reproducible example is:
```
@Model()
abstract class Foo {
  @PrimaryKey()
  String get id;
  List<Bar> get bars;
}

@Model()
abstract class Bar {
  @PrimaryKey()
  String get id;
}
```

This results in the following `build_runner` error:
```
Failed to build database schema:

type 'ReferenceColumnBuilder' is not a subtype of type 'ForeignColumnBuilder' of 'value'
```

**Comment by schultek** [comment]
Strange that this wasn't catched before, I'll look into it.

**Comment by schultek** [comment]
Should be fixed on main. Before I release can you test with:

```yaml
dependency_overrides:
  stormberry:
    git: github.com/schultek/stormberry
```
